## Модуль Pandas: знакомство

Для каких задач используют Pandas?

* **Аналитика данных**: продуктовая, маркетинговая и другая. Работа с любыми данными требует анализа и подготовки: необходимо удалить или заполнить пропуски, отфильтровать, отсортировать или каким-то образом изменить данные. Pandas позволяет быстро выполнить все эти действия, а в большинстве случаев ещё и автоматизировать их.

* **Data science** и работа с большими данными. Pandas помогает подготовить и провести первичный анализ данных, чтобы потом использовать их в машинном или глубоком обучении.

* **Статистика**. Библиотека поддерживает основные статистические методы, которые необходимы для работы с данными. Например, расчёт средних значений, их распределение по квантилям и другие.

In [67]:
# устанавливать Pandas при работе с Jupyter Notebook или Google Colab не требуется, просто импортируем
import pandas as pd

### Series и DataFrame
Данные в Pandas представлены в двух видах: *Series*#* и *DataFrame*. Разберёмся с каждым из них.

#### Что такое Series?
*pd.Series* — это одномерный помеченный массив в библиотеке pandas для Python. Он может хранить данные любого типа (числа, строки, объекты Python и т. д.) и состоит из двух основных компонентов:

    * данных (значения);

    * индекса (метки для идентификации элементов).

Основные компоненты

1. Данные (*values*)

    * хранятся в виде массива *NumPy*;

    * могут быть любого типа: целые числа, числа с плавающей запятой, строки, даты, объекты;

    * после создания размер фиксирован.

2. Индекс (*index*)

    * последовательность меток для идентификации каждого элемента;

    * по умолчанию: целые числа от 0 до N−1;

    * можно задать произвольные метки (строки, даты и т. д.);

    * метки могут повторяться, но должны быть хешируемыми.

3. Тип данных (*dtype*)

    * автоматически определяется при создании, но можно задать явно;

    * основные типы: *int64, float64, object* (для строк и смешанных данных), *bool, datetime64*.

4. Имя (*name*)

    * необязательный атрибут — имя серии.

In [68]:
# Создадим простой Series из списка:
s1 = pd.Series([1, -3, 5, 6], name='Первая')
s1

0    1
1   -3
2    5
3    6
Name: Первая, dtype: int64

In [69]:
# Из словаря (ключи → индекс, значения → данные)
s2 = pd.Series({'a': 10, 'b': 20, 'c': 30})
s2

a    10
b    20
c    30
dtype: int64

In [70]:
# Из массива NumPy
import numpy as np

arr = np.array([1.1, 2.2, 3.3])
s3 = pd.Series(arr)
s3

0    1.1
1    2.2
2    3.3
dtype: float64

In [71]:
# Из скалярного значения (повторяется для всех индексов)
s4 = pd.Series(5, index=['x', 'y', 'z'])
s4

x    5
y    5
z    5
dtype: int64

#### Доступ к данным

In [72]:
# По позиции (как в списке):
s1[0]  
s1[1:3]

1   -3
2    5
Name: Первая, dtype: int64

In [73]:
# По метке индекса:
s2['a']
s2[['a', 'c']]

a    10
c    30
dtype: int64

Методы *loc[ ]* и *iloc[ ]*:

    * loc[] — доступ по меткам: s2.loc['a'];

    * iloc[]* — доступ по позициям: s1.iloc[0].

In [74]:
s2.loc['a']

np.int64(10)

In [75]:
s1.iloc[0]

np.int64(1)

In [76]:
# Булева индексация (фильтрация):
mask = s1 > 3
s1[mask]

2    5
3    6
Name: Первая, dtype: int64

Ключевые свойства

    s.index — получить индекс;

    s.values — получить массив данных;

    s.dtype — тип данных;

    s.name — имя серии;

    len(s) — длина серии;

    s.shape — размерность (кортеж);

    s.size — количество элементов.

In [77]:
print(f's1.index: {s1.index}')
print(f's1.values: {s1.values}')
print(f's1.dtype: {s1.dtype}')
print(f's1.name: {s1.name}')
print(f'len(s1): {len(s1)}')
print(f's1.shape: {s1.shape}')
print(f's1.size: {s1.size}')

s1.index: RangeIndex(start=0, stop=4, step=1)
s1.values: [ 1 -3  5  6]
s1.dtype: int64
s1.name: Первая
len(s1): 4
s1.shape: (4,)
s1.size: 4

#### Обработка пропущенных данных

1. Пропущенные значения обозначаются как *NaN* (Not a Number);

2. Автоматически исключаются из статистических операций (*sum( )*, *mean( )* и т. д.);

3. Методы для работы с *NaN*:

    * *isnull( )* / *notnull( )* — проверка на пропуски;

    * *dropna( )* — удалить пропуски;

    * *fillna(value)* — заполнить пропуски заданным значением.

In [78]:
s_nan = pd.Series([1, np.nan, 3])
s_nan.isnull()

0    False
1     True
2    False
dtype: bool

In [79]:
# Почему ничего не изменилось?
s_nan

0    1.0
1    NaN
2    3.0
dtype: float64

**Note!**

По умолчанию метод *fillna( )* в pandas не изменяет исходный объект, а возвращает новый — копию с заполненными значениями. Это поведение задаётся параметром *inplace=False* (значение по умолчанию).

In [80]:
s_nan = pd.Series([1, np.nan, 3])
s_nan.isnull()
s_nan

0    1.0
1    NaN
2    3.0
dtype: float64

In [81]:
print(s_nan.dropna())
print(s_nan)

0    1.0
2    3.0
dtype: float64
0    1.0
1    NaN
2    3.0
dtype: float64

In [82]:
s_nan.dropna(inplace=True)
s_nan

0    1.0
2    3.0
dtype: float64

In [83]:
s_nan.fillna(0)

0    1.0
2    3.0
dtype: float64

#### Операции над Series
1. Арифметические (+, -, *, /, **)

    * выравнивают данные по меткам индекса;

    * если метки не совпадают, результат содержит NaN.

In [84]:
a = pd.Series([1, 2], index=['a', 'b'])
b = pd.Series([3, 4], index=['b', 'c'])
a + b

a    NaN
b    5.0
c    NaN
dtype: float64

In [85]:
a.add([1, 2])

a    2
b    4
dtype: int64

In [86]:
d = pd.Series([1, -7, 3, 5])
d.abs()

0    1
1    7
2    3
3    5
dtype: int64

2. Статистические (*sum( ), mean( ), std( ), min( ), max( )*)

    * игнорируют NaN по умолчанию.

In [87]:
s7 = pd.Series([7, np.nan, 9, 2, 1])
print(f'Результат функции sum(): {s7.sum()}')
print(f'Результат функции mean(): {s7.mean()}')
print(f'Результат функции std(): {s7.std():.2f}')
print(f'Результат функции min(): {s7.min()}')

Результат функции sum(): 19.0
Результат функции mean(): 4.75
Результат функции std(): 3.86
Результат функции min(): 1.0

3. Применение функций (*apply(func)*)

    * применяет функцию к каждому элементу.

In [88]:
temperatures = pd.Series(
    [20, 22, 19, 25],
    index=['Пн', 'Вт', 'Ср', 'Чт'],
    name='Температура (°C)'
)
temperatures

Пн    20
Вт    22
Ср    19
Чт    25
Name: Температура (°C), dtype: int64

In [89]:
# Температуры выше 20°C
hot_days = temperatures[temperatures > 20]

In [90]:
# Перевод в Фаренгейты
fahrenheit = temperatures.apply(lambda c: c * 9/5 + 32)

4. Сортировка (*sort_values( ), sort_index( )*)

In [91]:
ser = pd.Series([6, 4, 2, 9], index=['b', 'a', 'd', 'c'])
ser.sort_values()

d    2
a    4
b    6
c    9
dtype: int64

In [92]:
ser.sort_index()

a    4
b    6
c    9
d    2
dtype: int64

5. Группировка и агрегация (*groupby( ), agg( )*)

In [93]:
# группировка по значению
s8 = pd.Series([1, 5, 1, 4, 5], index=['b', 'a', 'c', 'b', 'a'])
s8.groupby(s8).sum()

1     2
4     4
5    10
dtype: int64

In [94]:
# группировка по индексу
grouped = s8.groupby(s8.index)
grouped.sum()

a    10
b     5
c     1
dtype: int64

In [95]:
# группировка по внешнему списку
categories = ['X', 'Y', 'X', 'Z', 'Y']
grouped = s8.groupby(categories)
grouped.sum()

X     2
Y    10
Z     4
dtype: int64

In [96]:
# группировка при помощи функции
s9 = pd.Series([x for x in range(10)])
grouped = s9.groupby(lambda x: 'четное' if x % 2 == 0 else 'нечетное')
grouped.count()

нечетное    5
четное      5
dtype: int64

#### Что такое DataFrame?

**pd.DataFrame** — основной тип данных в Pandas, вокруг которого строится вся работа. Его можно представить в виде обычной таблицы с любым количеством столбцов и строк. Внутри ячеек такой «таблицы» могут быть данные самого разного типа: числовые, булевы, строковые и так далее.

DataFrame — двумерная помеченная структура данных с индексированными строками и столбцами (похожа на таблицу Excel). Состоит из:

* набора Series (каждый столбец — это Series);

* индекса строк (index);

* названий столбцов (columns).

1. Создание DataFrame из pd.Series

In [97]:
s1 = pd.Series(['Москва', 'Санкт-Петербург', 'Новосибирск', 'Екатеринбург'], name='Город')
s2 = pd.Series([1147, 1703, 1893, 1723], name='Год основания')
df = pd.concat([s1, s2], axis=1)
df

             Город  Год основания
0           Москва           1147
1  Санкт-Петербург           1703
2      Новосибирск           1893
3     Екатеринбург           1723

In [98]:
col_1 = df['Город']
type(col_1)

pandas.core.series.Series

In [99]:
row_0 = df.loc[0]
type(row_0)

pandas.core.series.Series

2. Создание DataFrame из списка списков

In [100]:
data = [
    ['Анна', 25, 'Москва'],
    ['Борис', 30, 'СПб'],
    ['Виктор', 35, 'Казань']
]
columns = ['Имя', 'Возраст', 'Город']
df = pd.DataFrame(data, columns=columns)
df

      Имя  Возраст   Город
0    Анна       25  Москва
1   Борис       30     СПб
2  Виктор       35  Казань

3. Создание DataFrame из массива NumPy

In [101]:
data_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
df = pd.DataFrame(data_np, columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

4. Создадание DataFrame с помощью словаря

In [102]:
city = {'Город': ['Москва', 'Санкт-Петербург', 'Новосибирск', 'Екатеринбург'],
        'Год основания': [1147, 1703, 1893, 1723], 
        'Население': [11.9, 4.9, 1.5, 1.4]}

df = pd.DataFrame(city)
df

             Город  Год основания  Население
0           Москва           1147       11.9
1  Санкт-Петербург           1703        4.9
2      Новосибирск           1893        1.5
3     Екатеринбург           1723        1.4

5. Создание DataFrame с помощью json-структуры

In [103]:
# Теперь :
import json

path = '../../data/city_data.txt'
with open(path, 'r', encoding='utf-8') as f:
   city_data = json.load(f)

json_data = city_data['objects']
df = pd.DataFrame(json_data)
df

,id,type,name,district,capacity,coordinates,accessibility,services
0,101,school,Гимназия №5,Центральный,850,"[55.751244, 37.618423]","{'parking': True, 'elevator': False, 'ramp': T...","[дошкольная_группа, спортзал, столовая]"
1,102,hospital,Городская больница №2,Южный,320,"[55.749231, 37.620111]","{'parking': True, 'elevator': True, 'ramp': True}","[травмпункт, стационар, диагностика]"
2,103,kindergarten,Детский сад №15 «Солнышко»,Центральный,120,"[55.7521, 37.6195]","{'parking': False, 'elevator': False, 'ramp': ...","[ясельная_группа, логопед, бассейн, продлёнка]"
3,104,school,Средняя школа №8,Западный,600,"[55.745, 37.63]","{'parking': True, 'elevator': True, 'ramp': Fa...","[библиотека, актовый_зал, столовая]"
4,105,kindergarten,Детский сад №22 «Радуга»,Южный,90,"[55.75, 37.625]","{'parking': True, 'elevator': False, 'ramp': T...","[ясельная_группа, музыкальный_зал, продлёнка]"

In [104]:
# сохраним наш df в .json
df.to_json('../../data/city_data.json', index=False)

In [105]:
# сохраним наш df в .csv
df.to_csv('../../data/city_data.csv', 
          sep=',', 
          index=False, 
          encoding='utf-8'
          )

In [106]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in C:\Users\Dmitriy\AppData\Roaming\Python\Python312\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\Dmitriy\AppData\Roaming\Python\Python312\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [107]:
# сохраним наш df в Exel
df.to_excel('../../data/city_data.xlsx', index=False)

6. Создадание DataFrame из файла

In [108]:
df_json = pd.read_json('../../data/city_data.json')
df_json

,id,type,name,district,capacity,coordinates,accessibility,services
0,101,school,Гимназия №5,Центральный,850,"[55.751244, 37.618423]","{'parking': True, 'elevator': False, 'ramp': T...","[дошкольная_группа, спортзал, столовая]"
1,102,hospital,Городская больница №2,Южный,320,"[55.749231, 37.620111]","{'parking': True, 'elevator': True, 'ramp': True}","[травмпункт, стационар, диагностика]"
2,103,kindergarten,Детский сад №15 «Солнышко»,Центральный,120,"[55.7521, 37.6195]","{'parking': False, 'elevator': False, 'ramp': ...","[ясельная_группа, логопед, бассейн, продлёнка]"
3,104,school,Средняя школа №8,Западный,600,"[55.745, 37.63]","{'parking': True, 'elevator': True, 'ramp': Fa...","[библиотека, актовый_зал, столовая]"
4,105,kindergarten,Детский сад №22 «Радуга»,Южный,90,"[55.75, 37.625]","{'parking': True, 'elevator': False, 'ramp': T...","[ясельная_группа, музыкальный_зал, продлёнка]"

In [109]:
df_csv = pd.read_csv('../../data/city_data.csv',
                    sep=',', 
                    encoding='utf-8'
                     )
df_csv

,id,type,name,district,capacity,coordinates,accessibility,services
0,101,school,Гимназия №5,Центральный,850,"[55.751244, 37.618423]","{'parking': True, 'elevator': False, 'ramp': T...","['дошкольная_группа', 'спортзал', 'столовая']"
1,102,hospital,Городская больница №2,Южный,320,"[55.749231, 37.620111]","{'parking': True, 'elevator': True, 'ramp': True}","['травмпункт', 'стационар', 'диагностика']"
2,103,kindergarten,Детский сад №15 «Солнышко»,Центральный,120,"[55.7521, 37.6195]","{'parking': False, 'elevator': False, 'ramp': ...","['ясельная_группа', 'логопед', 'бассейн', 'про..."
3,104,school,Средняя школа №8,Западный,600,"[55.745, 37.63]","{'parking': True, 'elevator': True, 'ramp': Fa...","['библиотека', 'актовый_зал', 'столовая']"
4,105,kindergarten,Детский сад №22 «Радуга»,Южный,90,"[55.75, 37.625]","{'parking': True, 'elevator': False, 'ramp': T...","['ясельная_группа', 'музыкальный_зал', 'продлё..."

In [110]:
df_xlsx = pd.read_excel('../../data/city_data.xlsx')
df_xlsx

,id,type,name,district,capacity,coordinates,accessibility,services
0,101,school,Гимназия №5,Центральный,850,"[55.751244, 37.618423]","{'parking': True, 'elevator': False, 'ramp': T...","['дошкольная_группа', 'спортзал', 'столовая']"
1,102,hospital,Городская больница №2,Южный,320,"[55.749231, 37.620111]","{'parking': True, 'elevator': True, 'ramp': True}","['травмпункт', 'стационар', 'диагностика']"
2,103,kindergarten,Детский сад №15 «Солнышко»,Центральный,120,"[55.7521, 37.6195]","{'parking': False, 'elevator': False, 'ramp': ...","['ясельная_группа', 'логопед', 'бассейн', 'про..."
3,104,school,Средняя школа №8,Западный,600,"[55.745, 37.63]","{'parking': True, 'elevator': True, 'ramp': Fa...","['библиотека', 'актовый_зал', 'столовая']"
4,105,kindergarten,Детский сад №22 «Радуга»,Южный,90,"[55.75, 37.625]","{'parking': True, 'elevator': False, 'ramp': T...","['ясельная_группа', 'музыкальный_зал', 'продлё..."

#### Индексы и метки в pandas

In [111]:
index_list = ['первая', 'вторая', 'третья', 'четвертая', 'пятая'] 
df = pd.DataFrame(json_data,
                  index=index_list
                  )
df

,id,type,name,district,capacity,coordinates,accessibility,services
первая,101,school,Гимназия №5,Центральный,850,"[55.751244, 37.618423]","{'parking': True, 'elevator': False, 'ramp': T...","[дошкольная_группа, спортзал, столовая]"
вторая,102,hospital,Городская больница №2,Южный,320,"[55.749231, 37.620111]","{'parking': True, 'elevator': True, 'ramp': True}","[травмпункт, стационар, диагностика]"
третья,103,kindergarten,Детский сад №15 «Солнышко»,Центральный,120,"[55.7521, 37.6195]","{'parking': False, 'elevator': False, 'ramp': ...","[ясельная_группа, логопед, бассейн, продлёнка]"
четвертая,104,school,Средняя школа №8,Западный,600,"[55.745, 37.63]","{'parking': True, 'elevator': True, 'ramp': Fa...","[библиотека, актовый_зал, столовая]"
пятая,105,kindergarten,Детский сад №22 «Радуга»,Южный,90,"[55.75, 37.625]","{'parking': True, 'elevator': False, 'ramp': T...","[ясельная_группа, музыкальный_зал, продлёнка]"

In [112]:
# Доступ к данным по метке (содержанию индекса):
df.loc['первая']

id                                                             101
type                                                        school
name                                                   Гимназия №5
district                                               Центральный
capacity                                                       850
coordinates                                 [55.751244, 37.618423]
accessibility    {'parking': True, 'elevator': False, 'ramp': T...
services                   [дошкольная_группа, спортзал, столовая]
Name: первая, dtype: object

In [113]:
# Доступ к данным по индексу:
df.iloc[0]

id                                                             101
type                                                        school
name                                                   Гимназия №5
district                                               Центральный
capacity                                                       850
coordinates                                 [55.751244, 37.618423]
accessibility    {'parking': True, 'elevator': False, 'ramp': T...
services                   [дошкольная_группа, спортзал, столовая]
Name: первая, dtype: object

In [114]:
# Доступ к данным по имени столбца:
df['name']

первая                      Гимназия №5
вторая            Городская больница №2
третья       Детский сад №15 «Солнышко»
четвертая              Средняя школа №8
пятая          Детский сад №22 «Радуга»
Name: name, dtype: object

In [115]:
# список названий столбцов
df.columns

Index(['id', 'type', 'name', 'district', 'capacity', 'coordinates',
       'accessibility', 'services'],
      dtype='object')

In [116]:
# список [index, columns]
df.axes

[Index(['первая', 'вторая', 'третья', 'четвертая', 'пятая'], dtype='object'),
 Index(['id', 'type', 'name', 'district', 'capacity', 'coordinates',
        'accessibility', 'services'],
       dtype='object')]

Переименование и сброс индексов

In [117]:
# Метод rename() позволяет изменить метки строк и столбцов
# Переименование строк
df_renamed = df.rename(index={'первая': '1я', 'вторая': '2я'})

# Переименование столбцов
df_renamed = df_renamed.rename(columns={'coordinates' : 'geometry'})

df_renamed

,id,type,name,district,capacity,geometry,accessibility,services
1я,101,school,Гимназия №5,Центральный,850,"[55.751244, 37.618423]","{'parking': True, 'elevator': False, 'ramp': T...","[дошкольная_группа, спортзал, столовая]"
2я,102,hospital,Городская больница №2,Южный,320,"[55.749231, 37.620111]","{'parking': True, 'elevator': True, 'ramp': True}","[травмпункт, стационар, диагностика]"
третья,103,kindergarten,Детский сад №15 «Солнышко»,Центральный,120,"[55.7521, 37.6195]","{'parking': False, 'elevator': False, 'ramp': ...","[ясельная_группа, логопед, бассейн, продлёнка]"
четвертая,104,school,Средняя школа №8,Западный,600,"[55.745, 37.63]","{'parking': True, 'elevator': True, 'ramp': Fa...","[библиотека, актовый_зал, столовая]"
пятая,105,kindergarten,Детский сад №22 «Радуга»,Южный,90,"[55.75, 37.625]","{'parking': True, 'elevator': False, 'ramp': T...","[ясельная_группа, музыкальный_зал, продлёнка]"

Установка столбца в качестве индекса

In [123]:
df_indexed = df.set_index('id')
df_indexed

,type,name,district,capacity,coordinates,accessibility,services
id,,,,,,,
101,school,Гимназия №5,Центральный,850,"[55.751244, 37.618423]","{'parking': True, 'elevator': False, 'ramp': T...","[дошкольная_группа, спортзал, столовая]"
102,hospital,Городская больница №2,Южный,320,"[55.749231, 37.620111]","{'parking': True, 'elevator': True, 'ramp': True}","[травмпункт, стационар, диагностика]"
103,kindergarten,Детский сад №15 «Солнышко»,Центральный,120,"[55.7521, 37.6195]","{'parking': False, 'elevator': False, 'ramp': ...","[ясельная_группа, логопед, бассейн, продлёнка]"
104,school,Средняя школа №8,Западный,600,"[55.745, 37.63]","{'parking': True, 'elevator': True, 'ramp': Fa...","[библиотека, актовый_зал, столовая]"
105,kindergarten,Детский сад №22 «Радуга»,Южный,90,"[55.75, 37.625]","{'parking': True, 'elevator': False, 'ramp': T...","[ясельная_группа, музыкальный_зал, продлёнка]"

In [119]:
# Сброс индекса, старый индекс становится столбцом
df_reset = df_indexed.reset_index()
df_reset

,id,type,name,district,capacity,coordinates,accessibility,services
0,101,school,Гимназия №5,Центральный,850,"[55.751244, 37.618423]","{'parking': True, 'elevator': False, 'ramp': T...","[дошкольная_группа, спортзал, столовая]"
1,102,hospital,Городская больница №2,Южный,320,"[55.749231, 37.620111]","{'parking': True, 'elevator': True, 'ramp': True}","[травмпункт, стационар, диагностика]"
2,103,kindergarten,Детский сад №15 «Солнышко»,Центральный,120,"[55.7521, 37.6195]","{'parking': False, 'elevator': False, 'ramp': ...","[ясельная_группа, логопед, бассейн, продлёнка]"
3,104,school,Средняя школа №8,Западный,600,"[55.745, 37.63]","{'parking': True, 'elevator': True, 'ramp': Fa...","[библиотека, актовый_зал, столовая]"
4,105,kindergarten,Детский сад №22 «Радуга»,Южный,90,"[55.75, 37.625]","{'parking': True, 'elevator': False, 'ramp': T...","[ясельная_группа, музыкальный_зал, продлёнка]"

In [120]:
# Сброс без сохранения старого индекса
df_reset_drop = df_indexed.reset_index(drop=True)
df_reset_drop

,type,name,district,capacity,coordinates,accessibility,services
0,school,Гимназия №5,Центральный,850,"[55.751244, 37.618423]","{'parking': True, 'elevator': False, 'ramp': T...","[дошкольная_группа, спортзал, столовая]"
1,hospital,Городская больница №2,Южный,320,"[55.749231, 37.620111]","{'parking': True, 'elevator': True, 'ramp': True}","[травмпункт, стационар, диагностика]"
2,kindergarten,Детский сад №15 «Солнышко»,Центральный,120,"[55.7521, 37.6195]","{'parking': False, 'elevator': False, 'ramp': ...","[ясельная_группа, логопед, бассейн, продлёнка]"
3,school,Средняя школа №8,Западный,600,"[55.745, 37.63]","{'parking': True, 'elevator': True, 'ramp': Fa...","[библиотека, актовый_зал, столовая]"
4,kindergarten,Детский сад №22 «Радуга»,Южный,90,"[55.75, 37.625]","{'parking': True, 'elevator': False, 'ramp': T...","[ясельная_группа, музыкальный_зал, продлёнка]"

Мультииндексы

**Мультииндекс (иерархический индекс)** — индекс с несколькими уровнями. Полезен для сложных данных (например, временные ряды по регионам и категориям).

In [126]:
df.columns

Index(['id', 'type', 'name', 'district', 'capacity', 'coordinates',
       'accessibility', 'services'],
      dtype='object')

In [127]:
# Через set_index() с несколькими столбцами:
df_multi = df.set_index(['id', 'type'])
df_multi

,,name,district,capacity,coordinates,accessibility,services
id,type,,,,,,
101,school,Гимназия №5,Центральный,850,"[55.751244, 37.618423]","{'parking': True, 'elevator': False, 'ramp': T...","[дошкольная_группа, спортзал, столовая]"
102,hospital,Городская больница №2,Южный,320,"[55.749231, 37.620111]","{'parking': True, 'elevator': True, 'ramp': True}","[травмпункт, стационар, диагностика]"
103,kindergarten,Детский сад №15 «Солнышко»,Центральный,120,"[55.7521, 37.6195]","{'parking': False, 'elevator': False, 'ramp': ...","[ясельная_группа, логопед, бассейн, продлёнка]"
104,school,Средняя школа №8,Западный,600,"[55.745, 37.63]","{'parking': True, 'elevator': True, 'ramp': Fa...","[библиотека, актовый_зал, столовая]"
105,kindergarten,Детский сад №22 «Радуга»,Южный,90,"[55.75, 37.625]","{'parking': True, 'elevator': False, 'ramp': T...","[ясельная_группа, музыкальный_зал, продлёнка]"

In [129]:
# Явное создание через pd.MultiIndex:
arrays = [['A', 'A', 'B', 'B'], ['x', 'y', 'x', 'y']]
multi_index = pd.MultiIndex.from_arrays(arrays, names=('level1', 'level2'))
df_custom = pd.DataFrame({'Значение': [1, 2, 3, 4]}, index=multi_index)
df_custom

               Значение
level1 level2
A      x              1
       y              2
B      x              3
       y              4

Работа с мультииндексом

In [131]:
# Доступ по уровням
df_custom.loc[('A', 'y'), 'Значение']

np.int64(2)

In [132]:
# Выбор по первому уровню
df_custom.loc['B']

        Значение
level2
x              3
y              4

In [139]:
# Свёртка по уровню
df_custom.groupby(level='level1').sum()

        Значение
level1
A              3
B              7

In [141]:
# Свёртка по уровню
df_custom.groupby(level='level2').mean()

        Значение
level2
x            2.0
y            3.0